#pragma once
enum FontRenderFlag_t
{
	FONT_LEFT = 0,
	FONT_RIGHT = 1,
	FONT_CENTER = 2
};
enum ECstrike15UserMessages
{
    CS_UM_VGUIMenu = 1,
    CS_UM_Geiger = 2,
    CS_UM_Train = 3,
    CS_UM_HudText = 4,
    CS_UM_SayText = 5,
    CS_UM_SayText2 = 6,
    CS_UM_TextMsg = 7,
    CS_UM_HudMsg = 8,
    CS_UM_ResetHud = 9,
    CS_UM_GameTitle = 10,
    CS_UM_Shake = 12,
    CS_UM_Fade = 13,
    CS_UM_Rumble = 14,
    CS_UM_CloseCaption = 15,
    CS_UM_CloseCaptionDirect = 16,
    CS_UM_SendAudio = 17,
    CS_UM_RawAudio = 18,
    CS_UM_VoiceMask = 19,
    CS_UM_RequestState = 20,
    CS_UM_Damage = 21,
    CS_UM_RadioText = 22,
    CS_UM_HintText = 23,
    CS_UM_KeyHintText = 24,
    CS_UM_ProcessSpottedEntityUpdate = 25,
    CS_UM_ReloadEffect = 26,
    CS_UM_AdjustMoney = 27,
    CS_UM_UpdateTeamMoney = 28,
    CS_UM_StopSpectatorMode = 29,
    CS_UM_KillCam = 30,
    CS_UM_DesiredTimescale = 31,
    CS_UM_CurrentTimescale = 32,
    CS_UM_AchievementEvent = 33,
    CS_UM_MatchEndConditions = 34,
    CS_UM_DisconnectToLobby = 35,
    CS_UM_PlayerStatsUpdate = 36,
    CS_UM_DisplayInventory = 37,
    CS_UM_WarmupHasEnded = 38,
    CS_UM_ClientInfo = 39,
    CS_UM_XRankGet = 40,
    CS_UM_XRankUpd = 41,
    CS_UM_CallVoteFailed = 45,
    CS_UM_VoteStart = 46,
    CS_UM_VotePass = 47,
    CS_UM_VoteFailed = 48,
    CS_UM_VoteSetup = 49,
    CS_UM_ServerRankRevealAll = 50,
    CS_UM_SendLastKillerDamageToClient = 51,
    CS_UM_ServerRankUpdate = 52,
    CS_UM_ItemPickup = 53,
    CS_UM_ShowMenu = 54,
    CS_UM_BarTime = 55,
    CS_UM_AmmoDenied = 56,
    CS_UM_MarkAchievement = 57,
    CS_UM_MatchStatsUpdate = 58,
    CS_UM_ItemDrop = 59,
    CS_UM_GlowPropTurnOff = 60,
    CS_UM_SendPlayerItemDrops = 61,
    CS_UM_RoundBackupFilenames = 62,
    CS_UM_SendPlayerItemFound = 63,
    CS_UM_ReportHit = 64,
    CS_UM_XpUpdate = 65,
    CS_UM_QuestProgress = 66,
    CS_UM_ScoreLeaderboardData = 67,
    CS_UM_PlayerDecalDigitalSignature = 68,
    MAX_ECSTRIKE15USERMESSAGES
};
enum ItemDefinitionIndex
{
	ITEM_NONE = 0,
	WEAPON_DEAGLE = 1,
	WEAPON_ELITE = 2,
	WEAPON_FIVESEVEN = 3,
	WEAPON_GLOCK = 4,
	WEAPON_AK47 = 7,
	WEAPON_AUG = 8,
	WEAPON_AWP = 9,
	WEAPON_FAMAS = 10,
	WEAPON_G3SG1 = 11,
	WEAPON_GALILAR = 13,
	WEAPON_M249 = 14,
	WEAPON_M4A1 = 16,
	WEAPON_MAC10 = 17,
	WEAPON_P90 = 19,
	WEAPON_UMP45 = 24,
	WEAPON_XM1014 = 25,
	WEAPON_BIZON = 26,
	WEAPON_MAG7 = 27,
	WEAPON_NEGEV = 28,
	WEAPON_SAWEDOFF = 29,
	WEAPON_TEC9 = 30,
	WEAPON_TASER = 31,
	WEAPON_HKP2000 = 32,
	WEAPON_MP7 = 23,
	WEAPON_MP9 = 34,
	WEAPON_NOVA = 35,
	WEAPON_P250 = 36,
	WEAPON_SCAR20 = 38,
	WEAPON_SG556 = 39,
	WEAPON_SSG08 = 40,
	WEAPON_KNIFE = 42,
	WEAPON_FLASHBANG = 43,
	WEAPON_HEGRENADE = 44,
	WEAPON_SMOKEGRENADE = 45,
	WEAPON_MOLOTOV = 46,
	WEAPON_DECOY = 47,
	WEAPON_INCGRENADE = 48,
	WEAPON_C4 = 49,
	WEAPON_KNIFE_T = 59,
	WEAPON_M4A1_SILENCER = 60,
	WEAPON_USP_SILENCER = 61,
	WEAPON_CZ75A = 63,
	WEAPON_REVOLVER = 64,
	WEAPON_KNIFE_FLIP = 505,
	WEAPON_KNIFE_GUT = 506,
	WEAPON_KNIFE_KARAMBIT = 507,
	WEAPON_KNIFE_BAYONET = 500,
	WEAPON_KNIFE_M9_BAYONET = 508,
	WEAPON_KNIFE_TACTICAL = 509,
	WEAPON_KNIFE_FALCHION = 512,
	WEAPON_KNIFE_SURVIVAL_BOWIE = 514,
	WEAPON_KNIFE_BUTTERFLY = 515,
	WEAPON_KNIFE_PUSH = 516,
	WEAPON_KNIFE_URSUS = 519,
	WEAPON_KNIFE_GYPSY_JACKKNIFE = 520,
	WEAPON_KNIFE_STILETTO = 522,
	WEAPON_KNIFE_WIDOWMAKER = 523,
	GLOVE_STUDDED_BLOODHOUND = 5027,
	GLOVE_T_SIDE = 5028,
	GLOVE_CT_SIDE = 5029,
	GLOVE_SPORTY = 5030,
	GLOVE_SLICK = 5031,
	GLOVE_LEATHER_WRAP = 5032,
	GLOVE_MOTORCYCLE = 5033,
	GLOVE_SPECIALIST = 5034,
	MAX_ITEMDEFINITIONINDEX
};
enum ClassId
{
	ClassId_NextBotCombatCharacter = 0,
	ClassId_CAK47 = 1,
	ClassId_CBaseAnimating = 2,
	ClassId_CBaseAnimatingOverlay = 3,
	ClassId_CBaseAttributableItem = 4,
	ClassId_CBaseButton = 5,
	ClassId_CBaseCombatCharacter = 6,
	ClassId_CBaseCombatWeapon = 7,
	ClassId_CBaseCSGrenade = 8,
	ClassId_CBaseCSGrenadeProjectile = 9,
	ClassId_CBaseDoor = 10,
	ClassId_CBaseEntity = 11,
	ClassId_CBaseFlex = 12,
	ClassId_CBaseGrenade = 13,
	ClassId_CBaseParticleEntity = 14,
	ClassId_CBasePlayer = 15,
	ClassId_CBasePropDoor = 16,
	ClassId_CBaseTeamObjectiveResource = 17,
	ClassId_CBaseTempEntity = 18,
	ClassId_CBaseToggle = 19,
	ClassId_CBaseTrigger = 20,
	ClassId_CBaseViewModel = 21,
	ClassId_CBaseVPhysicsTrigger = 22,
	ClassId_CBaseWeaponWorldModel = 23,
	ClassId_CBeam = 24,
	ClassId_CBeamSpotlight = 25,
	ClassId_CBoneFollower = 26,
	ClassId_CBRC4Target = 27,
	ClassId_CBreachCharge = 28,
	ClassId_CBreachChargeProjectile = 29,
	ClassId_CBreakableProp = 30,
	ClassId_CBreakableSurface = 31,
	ClassId_CBumpMine = 32,
	ClassId_CBumpMineProjectile = 33,
	ClassId_CC4 = 34,
	ClassId_CCascadeLight = 35,
	ClassId_CChicken = 36,
	ClassId_CColorCorrection = 37,
	ClassId_CColorCorrectionVolume = 38,
	ClassId_CCSGameRulesProxy = 39,
	ClassId_CCSPlayer = 40,
	ClassId_CCSPlayerResource = 41,
	ClassId_CCSRagdoll = 42,
	ClassId_CCSTeam = 43,
	ClassId_CDangerZone = 44,
	ClassId_CDangerZoneController = 45,
	ClassId_CDEagle = 46,
	ClassId_CDecoyGrenade = 47,
	ClassId_CDecoyProjectile = 48,
	ClassId_CDrone = 49,
	ClassId_CDronegun = 50,
	ClassId_CDynamicLight = 51,
	ClassId_CDynamicProp = 52,
	ClassId_CEconEntity = 53,
	ClassId_CEconWearable = 54,
	ClassId_CEmbers = 55,
	ClassId_CEntityDissolve = 56,
	ClassId_CEntityFlame = 57,
	ClassId_CEntityFreezing = 58,
	ClassId_CEntityParticleTrail = 59,
	ClassId_CEnvAmbientLight = 60,
	ClassId_CEnvDetailController = 61,
	ClassId_CEnvDOFController = 62,
	ClassId_CEnvGasCanister = 63,
	ClassId_CEnvParticleScript = 64,
	ClassId_CEnvProjectedTexture = 65,
	ClassId_CEnvQuadraticBeam = 66,
	ClassId_CEnvScreenEffect = 67,
	ClassId_CEnvScreenOverlay = 68,
	ClassId_CEnvTonemapController = 69,
	ClassId_CEnvWind = 70,
	ClassId_CFEPlayerDecal = 71,
	ClassId_CFireCrackerBlast = 72,
	ClassId_CFireSmoke = 73,
	ClassId_CFireTrail = 74,
	ClassId_CFish = 75,
	ClassId_CFists = 76,
	ClassId_CFlashbang = 77,
	ClassId_CFogController = 78,
	ClassId_CFootstepControl = 79,
	ClassId_CFunc_Dust = 80,
	ClassId_CFunc_LOD = 81,
	ClassId_CFuncAreaPortalWindow = 82,
	ClassId_CFuncBrush = 83,
	ClassId_CFuncConveyor = 84,
	ClassId_CFuncLadder = 85,
	ClassId_CFuncMonitor = 86,
	ClassId_CFuncMoveLinear = 87,
	ClassId_CFuncOccluder = 88,
	ClassId_CFuncReflectiveGlass = 89,
	ClassId_CFuncRotating = 90,
	ClassId_CFuncSmokeVolume = 91,
	ClassId_CFuncTrackTrain = 92,
	ClassId_CGameRulesProxy = 93,
	ClassId_CGrassBurn = 94,
	ClassId_CHandleTest = 95,
	ClassId_CHEGrenade = 96,
	ClassId_CHostage = 97,
	ClassId_CHostageCarriableProp = 98,
	ClassId_CIncendiaryGrenade = 99,
	ClassId_CInferno = 100,
	ClassId_CInfoLadderDismount = 101,
	ClassId_CInfoMapRegion = 102,
		ClassId_CInfoOverlayAccessor = 103,
		ClassId_CItem_Healthshot = 104,
		ClassId_CItemCash = 105,
		ClassId_CItemDogtags = 106,
		ClassId_CKnife = 107,
		ClassId_CKnifeGG = 108,
		ClassId_CLightGlow = 109,
		ClassId_CMaterialModifyControl = 110,
		ClassId_CMelee = 111,
		ClassId_CMolotovGrenade = 112,
		ClassId_CMolotovProjectile = 113,
		ClassId_CMovieDisplay = 114,
		ClassId_CParadropChopper = 115,
		ClassId_CParticleFire = 116,
		ClassId_CParticlePerformanceMonitor = 117,
		ClassId_CParticleSystem = 118,
		ClassId_CPhysBox = 119,
		ClassId_CPhysBoxMultiplayer = 120,
		ClassId_CPhysicsProp = 121,
		ClassId_CPhysicsPropMultiplayer = 122,
		ClassId_CPhysMagnet = 123,
		ClassId_CPhysPropAmmoBox = 124,
		ClassId_CPhysPropLootCrate = 125,
		ClassId_CPhysPropRadarJammer = 126,
		ClassId_CPhysPropWeaponUpgrade = 127,
		ClassId_CPlantedC4 = 128,
		ClassId_CPlasma = 129,
		ClassId_CPlayerPing = 130,
		ClassId_CPlayerResource = 131,
		ClassId_CPointCamera = 132,
		ClassId_CPointCommentaryNode = 133,
		ClassId_CPointWorldText = 134,
		ClassId_CPoseController = 135,
		ClassId_CPostProcessController = 136,
		ClassId_CPrecipitation = 137,
		ClassId_CPrecipitationBlocker = 138,
		ClassId_CPredictedViewModel = 139,
		ClassId_CProp_Hallucination = 140,
		ClassId_CPropCounter = 141,
		ClassId_CPropDoorRotating = 142,
		ClassId_CPropJeep = 143,
		ClassId_CPropVehicleDriveable = 144,
		ClassId_CRagdollManager = 145,
		ClassId_CRagdollProp = 146,
		ClassId_CRagdollPropAttached = 147,
		ClassId_CRopeKeyframe = 148,
		ClassId_CSCAR17 = 149,
		ClassId_CSceneEntity = 150,
		ClassId_CSensorGrenade = 151,
		ClassId_CSensorGrenadeProjectile = 152,
		ClassId_CShadowControl = 153,
		ClassId_CSlideshowDisplay = 154,
		ClassId_CSmokeGrenade = 155,
		ClassId_CSmokeGrenadeProjectile = 156,
		ClassId_CSmokeStack = 157,
		ClassId_CSnowball = 158,
		ClassId_CSnowballPile = 159,
		ClassId_CSnowballProjectile = 160,
		ClassId_CSpatialEntity = 161,
		ClassId_CSpotlightEnd = 162,
		ClassId_CSprite = 163,
		ClassId_CSpriteOriented = 164,
		ClassId_CSpriteTrail = 165,
		ClassId_CStatueProp = 166,
		ClassId_CSteamJet = 167,
		ClassId_CSun = 168,
		ClassId_CSunlightShadowControl = 169,
		ClassId_CSurvivalSpawnChopper = 170,
		ClassId_CTablet = 171,
		ClassId_CTeam = 172,
		ClassId_CTeamplayRoundBasedRulesProxy = 173,
		ClassId_CTEArmorRicochet = 174,
		ClassId_CTEBaseBeam = 175,
		ClassId_CTEBeamEntPoint = 176,
		ClassId_CTEBeamEnts = 177,
		ClassId_CTEBeamFollow = 178,
		ClassId_CTEBeamLaser = 179,
		ClassId_CTEBeamPoints = 180,
		ClassId_CTEBeamRing = 181,
		ClassId_CTEBeamRingPoint = 182,
		ClassId_CTEBeamSpline = 183,
		ClassId_CTEBloodSprite = 184,
		ClassId_CTEBloodStream = 185,
		ClassId_CTEBreakModel = 186,
		ClassId_CTEBSPDecal = 187,
		ClassId_CTEBubbles = 188,
		ClassId_CTEBubbleTrail = 189,
		ClassId_CTEClientProjectile = 190,
		ClassId_CTEDecal = 191,
		ClassId_CTEDust = 192,
		ClassId_CTEDynamicLight = 193,
		ClassId_CTEEffectDispatch = 194,
		ClassId_CTEEnergySplash = 195,
		ClassId_CTEExplosion = 196,
		ClassId_CTEFireBullets = 197,
		ClassId_CTEFizz = 198,
		ClassId_CTEFootprintDecal = 199,
		ClassId_CTEFoundryHelpers = 200,
		ClassId_CTEGaussExplosion = 201,
		ClassId_CTEGlowSprite = 202,
			ClassId_CTEImpact = 203,
			ClassId_CTEKillPlayerAttachments = 204,
			ClassId_CTELargeFunnel = 205,
			ClassId_CTEMetalSparks = 206,
			ClassId_CTEMuzzleFlash = 207,
			ClassId_CTEParticleSystem = 208,
			ClassId_CTEPhysicsProp = 209,
			ClassId_CTEPlantBomb = 210,
			ClassId_CTEPlayerAnimEvent = 211,
			ClassId_CTEPlayerDecal = 212,
			ClassId_CTEProjectedDecal = 213,
			ClassId_CTERadioIcon = 214,
			ClassId_CTEShatterSurface = 215,
			ClassId_CTEShowLine = 216,
			ClassId_CTesla = 217,
			ClassId_CTESmoke = 218,
			ClassId_CTESparks = 219,
			ClassId_CTESprite = 220,
			ClassId_CTESpriteSpray = 221,
			ClassId_CTest_ProxyToggle_Networkable = 222,
			ClassId_CTestTraceline = 223,
			ClassId_CTEWorldDecal = 224,
			ClassId_CTriggerPlayerMovement = 225,
			ClassId_CTriggerSoundOperator = 226,
			ClassId_CVGuiScreen = 227,
			ClassId_CVoteController = 228,
			ClassId_CWaterBullet = 229,
			ClassId_CWaterLODControl = 230,
			ClassId_CWeaponAug = 231,
			ClassId_CWeaponAWP = 232,
			ClassId_CWeaponBaseItem = 233,
			ClassId_CWeaponBizon = 234,
			ClassId_CWeaponCSBase = 235,
			ClassId_CWeaponCSBaseGun = 236,
			ClassId_CWeaponCycler = 237,
			ClassId_CWeaponElite = 238,
			ClassId_CWeaponFamas = 239,
			ClassId_CWeaponFiveSeven = 240,
			ClassId_CWeaponG3SG1 = 241,
			ClassId_CWeaponGalil = 242,
			ClassId_CWeaponGalilAR = 243,
			ClassId_CWeaponGlock = 244,
			ClassId_CWeaponHKP2000 = 245,
			ClassId_CWeaponM249 = 246,
			ClassId_CWeaponM3 = 247,
			ClassId_CWeaponM4A1 = 248,
			ClassId_CWeaponMAC10 = 249,
			ClassId_CWeaponMag7 = 250,
			ClassId_CWeaponMP5Navy = 251,
			ClassId_CWeaponMP7 = 252,
			ClassId_CWeaponMP9 = 253,
			ClassId_CWeaponNegev = 254,
			ClassId_CWeaponNOVA = 255,
			ClassId_CWeaponP228 = 256,
			ClassId_CWeaponP250 = 257,
			ClassId_CWeaponP90 = 258,
			ClassId_CWeaponSawedoff = 259,
			ClassId_CWeaponSCAR20 = 260,
			ClassId_CWeaponScout = 261,
			ClassId_CWeaponSG550 = 262,
			ClassId_CWeaponSG552 = 263,
			ClassId_CWeaponSG556 = 264,
			ClassId_CWeaponShield = 265,
			ClassId_CWeaponSSG08 = 266,
			ClassId_CWeaponTaser = 267,
			ClassId_CWeaponTec9 = 268,
			ClassId_CWeaponTMP = 269,
			ClassId_CWeaponUMP45 = 270,
			ClassId_CWeaponUSP = 271,
			ClassId_CWeaponXM1014 = 272,
			ClassId_CWorld = 273,
			ClassId_CWorldVguiText = 274,
			ClassId_DustTrail = 275,
			ClassId_MovieExplosion = 276,
			ClassId_ParticleSmokeGrenade = 277,
			ClassId_RocketTrail = 278,
			ClassId_SmokeTrail = 279,
			ClassId_SporeExplosion = 280,
			ClassId_SporeTrail = 281,
    MAX_CLASSID
};
enum ECSPlayerBones
{
    PELVIS = 0,
    SPINE_0,
    SPINE_1,
    SPINE_2,
    SPINE_3,
    NECK_0,
    HEAD_0,
    CLAVICLE_L,
    ARM_UPPER_L,
    ARM_LOWER_L,
    HAND_L,
    FINGER_MIDDLE_META_L,
    FINGER_MIDDLE_0_L,
    FINGER_MIDDLE_1_L,
    FINGER_MIDDLE_2_L,
    FINGER_PINKY_META_L,
    FINGER_PINKY_0_L,
    FINGER_PINKY_1_L,
    FINGER_PINKY_2_L,
    FINGER_INDEX_META_L,
    FINGER_INDEX_0_L,
    FINGER_INDEX_1_L,
    FINGER_INDEX_2_L,
    FINGER_THUMB_0_L,
    FINGER_THUMB_1_L,
    FINGER_THUMB_2_L,
    FINGER_RING_META_L,
    FINGER_RING_0_L,
    FINGER_RING_1_L,
    FINGER_RING_2_L,
    WEAPON_HAND_L,
    ARM_LOWER_L_TWIST,
    ARM_LOWER_L_TWIST1,
    ARM_UPPER_L_TWIST,
    ARM_UPPER_L_TWIST1,
    CLAVICLE_R,
    ARM_UPPER_R,
    ARM_LOWER_R,
    HAND_R,
    FINGER_MIDDLE_META_R,
    FINGER_MIDDLE_0_R,
    FINGER_MIDDLE_1_R,
    FINGER_MIDDLE_2_R,
    FINGER_PINKY_META_R,
    FINGER_PINKY_0_R,
    FINGER_PINKY_1_R,
    FINGER_PINKY_2_R,
    FINGER_INDEX_META_R,
    FINGER_INDEX_0_R,
    FINGER_INDEX_1_R,
    FINGER_INDEX_2_R,
    FINGER_THUMB_0_R,
    FINGER_THUMB_1_R,
    FINGER_THUMB_2_R,
    FINGER_RING_META_R,
    FINGER_RING_0_R,
    FINGER_RING_1_R,
    FINGER_RING_2_R,
    WEAPON_HAND_R,
    ARM_LOWER_R_TWIST,
    ARM_LOWER_R_TWIST1,
    ARM_UPPER_R_TWIST,
    ARM_UPPER_R_TWIST1,
    LEG_UPPER_L,
    LEG_LOWER_L,
    ANKLE_L,
    BALL_L,
    LFOOT_LOCK,
    LEG_UPPER_L_TWIST,
    LEG_UPPER_L_TWIST1,
    LEG_UPPER_R,
    LEG_LOWER_R,
    ANKLE_R,
    BALL_R,
    RFOOT_LOCK,
    LEG_UPPER_R_TWIST,
    LEG_UPPER_R_TWIST1,
    FINGER_PINKY_L_END,
    FINGER_PINKY_R_END,
    VALVEBIPED_WEAPON_BONE,
    LH_IK_DRIVER,
    PRIMARY_JIGGLE_JNT,
    MAX_ECSPLAYERBONES
};
enum EntityFlags
{
    FL_ONGROUND = (1 << 0),
    FL_DUCKING = (1 << 1),
    FL_WATERJUMP = (1 << 2),
    FL_ONTRAIN = (1 << 3),
    FL_INRAIN = (1 << 4),
    FL_FROZEN = (1 << 5),
    FL_ATCONTROLS = (1 << 6),
    FL_CLIENT = (1 << 7),
    FL_FAKECLIENT = (1 << 8),
    MAX_ENTITYFLAGS
};
enum LifeState : unsigned char
{
    LIFE_ALIVE = 0,// alive
    LIFE_DYING = 1, // playing death animation or still falling off of a ledge waiting to hit ground
    LIFE_DEAD = 2, // dead. lying still.
    MAX_LIFESTATE
};
enum WeaponSound_t
{
    EMPTY,
    SINGLE,
    SINGLE_NPC,
    WPN_DOUBLE, // Can't be "DOUBLE" because windows.h uses it.
    DOUBLE_NPC,
    BURST,
    RELOAD,
    RELOAD_NPC,
    MELEE_MISS,
    MELEE_HIT,
    MELEE_HIT_WORLD,
    SPECIAL1,
    SPECIAL2,
    SPECIAL3,
    TAUNT,
    FAST_RELOAD,
    // Add new shoot sound types here
    REVERSE_THE_NEW_SOUND,
    NUM_SHOOT_SOUND_TYPES,
    MAX_WEAPONSOUND
};
enum MoveType_t
{
    MOVETYPE_NONE = 0,
    MOVETYPE_ISOMETRIC,
    MOVETYPE_WALK,
    MOVETYPE_STEP,
    MOVETYPE_FLY,
    MOVETYPE_FLYGRAVITY,
    MOVETYPE_VPHYSICS,
    MOVETYPE_PUSH,
    MOVETYPE_NOCLIP,
    MOVETYPE_LADDER,
    MOVETYPE_OBSERVER,
    MOVETYPE_CUSTOM,
    MOVETYPE_LAST = MOVETYPE_CUSTOM,
    MOVETYPE_MAX_BITS = 4,
    MAX_MOVETYPE
};
