//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDX_Multihack.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SquareFont")]
        public string Font {
            get {
                return ((string)(this["Font"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.SolidColorBrush AlliesColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["AlliesColor"]));
            }
            set {
                this["AlliesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.SolidColorBrush EnemiesColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["EnemiesColor"]));
            }
            set {
                this["EnemiesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.SolidColorBrush FovColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["FovColor"]));
            }
            set {
                this["FovColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF00FF00")]
        public global::System.Windows.Media.SolidColorBrush SkeletonAlliesColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["SkeletonAlliesColor"]));
            }
            set {
                this["SkeletonAlliesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.SolidColorBrush SkeletonEnemiesColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["SkeletonEnemiesColor"]));
            }
            set {
                this["SkeletonEnemiesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.SolidColorBrush ActiveWeaponColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ActiveWeaponColor"]));
            }
            set {
                this["ActiveWeaponColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF00FF00")]
        public global::System.Windows.Media.SolidColorBrush HeadHelperColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["HeadHelperColor"]));
            }
            set {
                this["HeadHelperColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.SolidColorBrush BackgroundColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["BackgroundColor"]));
            }
            set {
                this["BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.SolidColorBrush EntitiesColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["EntitiesColor"]));
            }
            set {
                this["EntitiesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF00")]
        public global::System.Windows.Media.SolidColorBrush ChickensColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ChickensColor"]));
            }
            set {
                this["ChickensColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.SolidColorBrush AdditionalInfoColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["AdditionalInfoColor"]));
            }
            set {
                this["AdditionalInfoColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.SolidColorBrush RankColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["RankColor"]));
            }
            set {
                this["RankColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.SolidColorBrush NameColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["NameColor"]));
            }
            set {
                this["NameColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public double Width {
            get {
                return ((double)(this["Width"]));
            }
            set {
                this["Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public double Height {
            get {
                return ((double)(this["Height"]));
            }
            set {
                this["Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.SolidColorBrush HealthBarColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["HealthBarColor"]));
            }
            set {
                this["HealthBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF00FF")]
        public global::System.Windows.Media.SolidColorBrush EnemiesVisColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["EnemiesVisColor"]));
            }
            set {
                this["EnemiesVisColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF00FF")]
        public global::System.Windows.Media.SolidColorBrush SkeletonEnemiesVisColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["SkeletonEnemiesVisColor"]));
            }
            set {
                this["SkeletonEnemiesVisColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF00FFFF")]
        public global::System.Windows.Media.SolidColorBrush RecoilCrosshairColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["RecoilCrosshairColor"]));
            }
            set {
                this["RecoilCrosshairColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF00FF00")]
        public global::System.Windows.Media.SolidColorBrush SpecialEntitiesColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["SpecialEntitiesColor"]));
            }
            set {
                this["SpecialEntitiesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.SolidColorBrush PathAlliesColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["PathAlliesColor"]));
            }
            set {
                this["PathAlliesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.SolidColorBrush PathEnemiesColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["PathEnemiesColor"]));
            }
            set {
                this["PathEnemiesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF00FF00")]
        public global::System.Windows.Media.SolidColorBrush ChamsAlliesColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ChamsAlliesColor"]));
            }
            set {
                this["ChamsAlliesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF00FF")]
        public global::System.Windows.Media.SolidColorBrush ChamsEnemiesColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ChamsEnemiesColor"]));
            }
            set {
                this["ChamsEnemiesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.SolidColorBrush SpectatorsColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["SpectatorsColor"]));
            }
            set {
                this["SpectatorsColor"] = value;
            }
        }
    }
}
